project-includes = ["src"]
project-excludes = ["**/.[!/.]*", "**/tests"]
search-path = ["src"]
site-package-path = [".venv/lib/python3.13/site-packages"]

python-version = "3.13"
python-interpreter-path = ".venv/bin/python3"
